#!/system/bin/sh
if [ -e /data/local/cpu_protection ] ; then
  echo failed > /data/local/cpu_failed
  chmod 777 /data/local/cpu_failed
  exit
fi

echo applied > /data/local/cpu_protection
chmod 777 /data/local/cpu_protection
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "1026000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo "384000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

chmod 666 /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
chmod 666 /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
echo "1026000" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
chmod 666 /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
echo "384000" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq


#! 762500 825000 825000 837500 862500 875000 887500 900000 925000 950000 962500 987500 1012500 1037500 1075000 1087500 1112500 1137500 1137500 1137500 1137500 1150000 1150000 1200000
echo "192000 762500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "310500 825000" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "384000 825000" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "432000 837500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "486000 862500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "540000 875000" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "594000 887500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "648000 900000" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "702000 925000" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "756000 950000" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "810000 962500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "864000 987500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "918000 1012500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "972000 1037500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "1026000 1075000" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "1080000 1087500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "1134000 1112500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "1188000 1137500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "1242000 1137500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "1296000 1137500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "1350000 1137500" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "1404000 1150000" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "1458000 1150000" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo "1512000 1200000" > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
